/**
 * FlowQuest in-cell decorations.
 *
 * For each cell in an opened notebook we attach a small "FlowQuest chip" at the
 * top of the cell. The chip shows:
 *   - region icon + label
 *   - a health dot reflecting the number/severity of issues
 *   - a mission star when a mission targets this cell
 *
 * Clicking the chip expands an inline panel below the cell input that lets the
 * user:
 *   - read a concise "Explain" generated by the LLM (earns XP once)
 *   - see issues grounded in the analyzer
 *   - trigger a reflection question (earns XP on submit)
 *   - see missions for this cell and claim them
 */

import { NotebookPanel } from '@jupyterlab/notebook';
import type { Cell } from '@jupyterlab/cells';

import { apiRequest, clipText, escapeHtml } from './api';
import type {
  AnalysisResponse,
  CellAnalysis,
  ClaimResponse,
  ExplainResponse,
  Mission,
  QuestState,
  ReflectPromptResponse
} from './types';

const CHIP_CLASS = 'flowquest-chip';
const PANEL_CLASS = 'flowquest-cellPanel';
const ROOT_CLASS = 'flowquest-cellRoot';

const SEVERITY_EMOJI: Record<string, string> = {
  info: '💡',
  warn: '⚠️',
  error: '🔥'
};

const MISSION_KIND_ICON: Record<string, string> = {
  exploration: '🧭',
  understanding: '🧠',
  stabilization: '🛠️',
  reflection: '🪞'
};

export interface CellDecoratorCallbacks {
  applyState: (state: QuestState) => void;
  getState: () => QuestState;
  onXpGained: (amount: number, category: string, source: string) => void;
  getNotebookPath: () => string;
  getAnalysis: () => AnalysisResponse | null;
  openSidebar: () => void;
}

interface CellEntry {
  cell: Cell;
  chip: HTMLElement;
  panel: HTMLElement;
  panelOpen: boolean;
  cellIndex: number;
  analysis: CellAnalysis | null;
  missions: Mission[];
  explanation: string;
  reflectQuestion: string;
  reflectText: string;
  loading: Set<string>;
}

export class CellDecorator {
  constructor(private panel: NotebookPanel, private callbacks: CellDecoratorCallbacks) {
    this.attachAll();
    this.panel.content.model?.cells.changed.connect(() => this.attachAll());
    this.panel.disposed.connect(() => this.dispose());
  }

  dispose(): void {
    this.entries.forEach(entry => {
      entry.chip.remove();
      entry.panel.remove();
      entry.cell.node.classList.remove(ROOT_CLASS);
    });
    this.entries.clear();
  }

  refresh(analysis: AnalysisResponse | null, _state?: QuestState): void {
    this.attachAll();
    const widgets = this.panel.content.widgets;
    widgets.forEach((cell, index) => {
      const entry = this.entries.get(cell);
      if (!entry) {
        return;
      }
      entry.cellIndex = index;
      entry.analysis = analysis?.cells.find(c => c.index === index) ?? null;
      entry.missions = (analysis?.missions ?? []).filter(m => m.cell_indices.includes(index));
      this.renderChip(entry);
      if (entry.panelOpen) {
        this.renderPanel(entry);
      }
    });
  }

  private attachAll(): void {
    const widgets = this.panel.content.widgets;
    widgets.forEach((cell, index) => {
      if (this.entries.has(cell)) {
        const entry = this.entries.get(cell)!;
        entry.cellIndex = index;
        return;
      }
      this.attachCell(cell, index);
    });
    // Clean up entries for removed cells.
    Array.from(this.entries.keys()).forEach(cell => {
      if (cell.isDisposed || !widgets.includes(cell)) {
        const entry = this.entries.get(cell)!;
        entry.chip.remove();
        entry.panel.remove();
        this.entries.delete(cell);
      }
    });
  }

  private attachCell(cell: Cell, index: number): void {
    cell.node.classList.add(ROOT_CLASS);

    const chip = document.createElement('div');
    chip.className = CHIP_CLASS;
    chip.setAttribute('role', 'button');
    chip.setAttribute('tabindex', '0');

    const panel = document.createElement('div');
    panel.className = PANEL_CLASS;
    panel.style.display = 'none';

    // Mount chip at top of cell.node and panel after the input container.
    const inputWrapper = cell.node.querySelector('.jp-Cell-inputWrapper') ?? cell.node;
    inputWrapper.parentElement?.insertBefore(chip, inputWrapper);
    inputWrapper.parentElement?.insertBefore(panel, inputWrapper.nextSibling);

    const entry: CellEntry = {
      cell,
      chip,
      panel,
      panelOpen: false,
      cellIndex: index,
      analysis: null,
      missions: [],
      explanation: '',
      reflectQuestion: '',
      reflectText: '',
      loading: new Set()
    };
    this.entries.set(cell, entry);

    chip.addEventListener('click', () => this.togglePanel(entry));
    chip.addEventListener('keydown', event => {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        this.togglePanel(entry);
      }
    });

    this.renderChip(entry);
  }

  private togglePanel(entry: CellEntry): void {
    entry.panelOpen = !entry.panelOpen;
    entry.panel.style.display = entry.panelOpen ? 'block' : 'none';
    if (entry.panelOpen) {
      this.renderPanel(entry);
    }
    this.renderChip(entry);
  }

  private renderChip(entry: CellEntry): void {
    const analysis = entry.analysis;
    const region = analysis?.region ?? 'other';
    const icon = analysis?.regionIcon ?? '✨';
    const issues = analysis?.issues ?? [];
    const worstSeverity = issues.reduce<string>((acc, issue) => {
      if (issue.severity === 'error') {
        return 'error';
      }
      if (issue.severity === 'warn' && acc !== 'error') {
        return 'warn';
      }
      if (issue.severity === 'info' && acc === '') {
        return 'info';
      }
      return acc;
    }, '');
    const missionCount = entry.missions.length;
    const healthClass = worstSeverity ? `is-${worstSeverity}` : 'is-ok';

    entry.chip.innerHTML = `
      <span class="flowquest-chipIcon">${escapeHtml(icon)}</span>
      <span class="flowquest-chipLabel">${escapeHtml(region)}</span>
      <span class="flowquest-chipDot ${healthClass}" title="${escapeHtml(
        worstSeverity ? `Has ${worstSeverity} issue(s)` : 'No issues detected'
      )}"></span>
      ${
        missionCount
          ? `<span class="flowquest-chipStar" title="${missionCount} mission${
              missionCount === 1 ? '' : 's'
            } for this cell">★ ${missionCount}</span>`
          : ''
      }
      <span class="flowquest-chipToggle">${entry.panelOpen ? '▾' : '▸'}</span>
    `;
    entry.chip.classList.toggle('is-open', entry.panelOpen);
    entry.chip.classList.toggle('has-issues', Boolean(worstSeverity));
    entry.chip.classList.toggle('has-mission', missionCount > 0);
  }

  private renderPanel(entry: CellEntry): void {
    const analysis = entry.analysis;
    const issues = analysis?.issues ?? [];
    const missions = entry.missions;
    const loadingExplain = entry.loading.has('explain');
    const loadingReflect = entry.loading.has('reflect');
    const loadingMission = (id: string) => entry.loading.has(`claim-${id}`);

    const issueHtml = issues
      .map(
        issue => `
          <li class="flowquest-issue flowquest-issue-${escapeHtml(issue.severity)}">
            <span class="flowquest-issueIcon">${escapeHtml(
              SEVERITY_EMOJI[issue.severity] ?? '•'
            )}</span>
            <span class="flowquest-issueBody">
              <strong>${escapeHtml(issue.kind.replace(/_/g, ' '))}</strong>
              <span>${escapeHtml(issue.message)}</span>
            </span>
          </li>
        `
      )
      .join('');

    const missionHtml = missions
      .map(mission => {
        const state = this.callbacks.getState();
        const completed = (state.completedAwardKeys ?? []).includes(`mission:${mission.id}`);
        const loadingThis = loadingMission(mission.id);
        const points = mission.health_points || mission.xp;
        return `
          <li class="flowquest-missionCard flowquest-mission-${escapeHtml(mission.kind)} ${
            completed ? 'is-complete' : ''
          }">
            <div class="flowquest-missionHead">
              <span class="flowquest-missionKind">${escapeHtml(
                MISSION_KIND_ICON[mission.kind] ?? '✨'
              )} ${escapeHtml(mission.kind)}</span>
              <span class="flowquest-missionXp">+${points} health</span>
            </div>
            <div class="flowquest-missionTitle">${escapeHtml(mission.title)}</div>
            <div class="flowquest-missionDesc">${escapeHtml(mission.description)}</div>
            <div class="flowquest-missionActions">
              <button
                type="button"
                class="flowquest-btn flowquest-btn-primary"
                data-action="claim"
                data-mission="${escapeHtml(mission.id)}"
                data-criterion="${escapeHtml(mission.criterion_id || 'workflow_clarity')}"
                data-points="${points}"
                data-label="${escapeHtml(mission.title)}"
                ${completed || loadingThis ? 'disabled' : ''}
              >${completed ? 'Claimed' : loadingThis ? 'Claiming…' : `Claim +${points}`}</button>
            </div>
          </li>
        `;
      })
      .join('');

    entry.panel.innerHTML = `
      <div class="flowquest-cellPanelInner">
        <div class="flowquest-sectionRow">
          <div class="flowquest-sectionTitle">Cell ${entry.cellIndex + 1} · ${escapeHtml(
            analysis?.region ?? 'other'
          )} ${escapeHtml(analysis?.regionIcon ?? '✨')}</div>
          <button type="button" class="flowquest-btn flowquest-btn-ghost" data-action="close">Close</button>
        </div>

        ${
          analysis
            ? `
              <div class="flowquest-factRow">
                ${
                  analysis.defines.length
                    ? `<span class="flowquest-fact">defines ${escapeHtml(
                        analysis.defines.slice(0, 6).join(', ')
                      )}</span>`
                    : ''
                }
                ${
                  analysis.uses.length
                    ? `<span class="flowquest-fact">uses ${escapeHtml(
                        analysis.uses.slice(0, 6).join(', ')
                      )}</span>`
                    : ''
                }
                ${
                  analysis.dependsOn.length
                    ? `<span class="flowquest-fact">depends on cell${
                        analysis.dependsOn.length > 1 ? 's' : ''
                      } ${analysis.dependsOn.map(i => i + 1).join(', ')}</span>`
                    : ''
                }
                ${
                  analysis.dependents.length
                    ? `<span class="flowquest-fact">feeds cell${
                        analysis.dependents.length > 1 ? 's' : ''
                      } ${analysis.dependents.map(i => i + 1).join(', ')}</span>`
                    : ''
                }
                ${
                  analysis.execCount !== null
                    ? `<span class="flowquest-fact">exec #${analysis.execCount}</span>`
                    : `<span class="flowquest-fact is-warn">not executed</span>`
                }
              </div>
            `
            : '<div class="flowquest-dim">FlowQuest analysis is still loading for this cell.</div>'
        }

        ${
          issues.length
            ? `<ul class="flowquest-issueList">${issueHtml}</ul>`
            : '<div class="flowquest-dim">✨ No issues detected in this cell.</div>'
        }

        <div class="flowquest-actionsRow">
          <button
            type="button"
            class="flowquest-btn flowquest-btn-primary"
            data-action="explain"
            ${loadingExplain ? 'disabled' : ''}
          >${loadingExplain ? 'Explaining…' : '🔍 Explain this cell'}</button>
          <button
            type="button"
            class="flowquest-btn"
            data-action="reflect"
            ${loadingReflect ? 'disabled' : ''}
          >${loadingReflect ? 'Thinking…' : '🪞 Reflect'}</button>
          <button type="button" class="flowquest-btn flowquest-btn-ghost" data-action="openSidebar">
            Open FlowQuest →
          </button>
        </div>

        ${
          entry.explanation
            ? `
              <div class="flowquest-blockTitle">Explanation</div>
              <div class="flowquest-block">${escapeHtml(entry.explanation)}</div>
            `
            : ''
        }

        ${
          entry.reflectQuestion
            ? `
              <div class="flowquest-blockTitle">Reflect</div>
              <div class="flowquest-block">${escapeHtml(entry.reflectQuestion)}</div>
              <textarea
                class="flowquest-textarea"
                data-field="reflect"
                placeholder="Your answer. Even one sentence counts — +10 Reflection XP when submitted.">${escapeHtml(
                  entry.reflectText
                )}</textarea>
              <div class="flowquest-actionsRow">
                <button type="button" class="flowquest-btn flowquest-btn-primary" data-action="submitReflect">
                  Submit Reflection
                </button>
              </div>
            `
            : ''
        }

        ${missions.length ? `<ul class="flowquest-missionList">${missionHtml}</ul>` : ''}
      </div>
    `;

    const textarea = entry.panel.querySelector<HTMLTextAreaElement>('textarea[data-field="reflect"]');
    if (textarea) {
      textarea.addEventListener('input', event => {
        entry.reflectText = (event.currentTarget as HTMLTextAreaElement).value;
      });
    }

    entry.panel.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(button => {
      button.onclick = () => this.handleAction(entry, button);
    });
  }

  private async handleAction(entry: CellEntry, button: HTMLButtonElement): Promise<void> {
    const action = button.dataset.action;
    if (action === 'close') {
      entry.panelOpen = false;
      entry.panel.style.display = 'none';
      this.renderChip(entry);
      return;
    }
    if (action === 'openSidebar') {
      this.callbacks.openSidebar();
      return;
    }
    if (action === 'explain') {
      await this.runExplain(entry);
      return;
    }
    if (action === 'reflect') {
      await this.runReflect(entry);
      return;
    }
    if (action === 'submitReflect') {
      await this.submitReflect(entry);
      return;
    }
        if (action === 'claim') {
          const missionId = button.dataset.mission ?? '';
          const criterionId = button.dataset.criterion ?? 'workflow_clarity';
          const points = Number(button.dataset.points ?? '0');
          const label = button.dataset.label ?? missionId;
          await this.claim(entry, missionId, criterionId, points, label);
        }
  }

  private async runExplain(entry: CellEntry): Promise<void> {
    const source = entry.cell.model.sharedModel.getSource();
    if (!source.trim()) {
      entry.explanation = 'This cell is empty. Add code or text first.';
      this.renderPanel(entry);
      return;
    }
    entry.loading.add('explain');
    this.renderPanel(entry);
    try {
      const response = await apiRequest<ExplainResponse>('piis-assistant/explain-cell', {
        method: 'POST',
        body: JSON.stringify({
          state: this.callbacks.getState(),
          cell: {
            index: entry.cellIndex,
            region: entry.analysis?.region ?? 'other',
            source: clipText(source, 3000)
          },
          analysis: this.callbacks.getAnalysis()
        })
      });
      entry.explanation = response.explanation || 'No explanation returned.';
      if (response.outcome?.granted && response.outcome.pointsAwarded) {
        this.callbacks.onXpGained(response.outcome.pointsAwarded, 'reader_understanding', 'Explain cell');
      }
      if (response.state) {
        this.callbacks.applyState(response.state);
      }
    } catch (error) {
      entry.explanation = `Could not explain: ${(error as Error).message}`;
    } finally {
      entry.loading.delete('explain');
      this.renderPanel(entry);
    }
  }

  private async runReflect(entry: CellEntry): Promise<void> {
    const source = entry.cell.model.sharedModel.getSource();
    entry.loading.add('reflect');
    this.renderPanel(entry);
    try {
      const response = await apiRequest<ReflectPromptResponse>('piis-assistant/reflect/prompt', {
        method: 'POST',
        body: JSON.stringify({
          cell: {
            index: entry.cellIndex,
            region: entry.analysis?.region ?? 'other',
            source: clipText(source, 2500)
          }
        })
      });
      entry.reflectQuestion = response.question || 'What could go wrong with this cell?';
    } catch (error) {
      entry.reflectQuestion = `Could not load reflection: ${(error as Error).message}`;
    } finally {
      entry.loading.delete('reflect');
      this.renderPanel(entry);
    }
  }

  private async submitReflect(entry: CellEntry): Promise<void> {
    const text = entry.reflectText.trim();
    if (!text) {
      return;
    }
    try {
      const response = await apiRequest<ClaimResponse>('piis-assistant/reflect/answer', {
        method: 'POST',
        body: JSON.stringify({
          state: this.callbacks.getState(),
          cellIndex: entry.cellIndex,
          text
        })
      });
      if (response.outcome?.granted) {
        this.callbacks.onXpGained(
          response.outcome.pointsAwarded ?? 0,
          'reader_understanding',
          'Reflection'
        );
      }
      this.callbacks.applyState(response.state);
      entry.reflectText = '';
      entry.reflectQuestion = `Reflection saved. ${entry.reflectQuestion}`;
    } catch (error) {
      entry.reflectQuestion = `Could not save reflection: ${(error as Error).message}`;
    } finally {
      this.renderPanel(entry);
    }
  }

  private async claim(
    entry: CellEntry,
    missionId: string,
    criterionId: string,
    points: number,
    label: string
  ): Promise<void> {
    entry.loading.add(`claim-${missionId}`);
    this.renderPanel(entry);
    try {
      const response = await apiRequest<ClaimResponse>('piis-assistant/mission/claim', {
        method: 'POST',
        body: JSON.stringify({
          state: this.callbacks.getState(),
          missionId,
          criterionId,
          points,
          label
        })
      });
      if (response.outcome?.granted) {
        this.callbacks.onXpGained(
          response.outcome.pointsAwarded ?? 0,
          response.outcome.criterion ?? criterionId,
          missionId
        );
      }
      this.callbacks.applyState(response.state);
    } catch (error) {
      // Best-effort: surface the error in the explanation block.
      entry.explanation = `Could not claim: ${(error as Error).message}`;
    } finally {
      entry.loading.delete(`claim-${missionId}`);
      this.renderPanel(entry);
    }
  }

  private entries = new Map<Cell, CellEntry>();
}
