/**
 * FlowQuest in-cell decorations.
 *
 * For each cell in an opened notebook we attach a small "FlowQuest chip" at the
 * top of the cell. The chip shows:
 *   - region icon + label
 *   - a health dot reflecting the number/severity of issues
 *   - a mission star when a mission targets this cell
 *
 * Clicking the chip expands an inline panel below the cell input that lets the
 * user:
 *   - read a concise "Explain" generated by the LLM (earns XP once)
 *   - see issues grounded in the analyzer
 *   - trigger a reflection question (earns XP on submit)
 *   - see missions for this cell and claim them
 */

import { NotebookPanel } from '@jupyterlab/notebook';
import type { Cell } from '@jupyterlab/cells';

import { apiRequest, clipText, escapeHtml, notebookAwardPrefix } from './api';
import { renderMarkdown } from './markdown';
import {
  categoryIcon,
  icon as renderUiIcon,
  regionIcon as renderRegionIcon
} from './icons';
import {
  errorBlockHtml,
  inlineSpinnerHtml,
  thinkingHtml,
  toFriendlyError
} from './uiFeedback';
import type {
  AnalysisResponse,
  CellAnalysis,
  ClaimResponse,
  ExplainResponse,
  Mission,
  QuestState,
  ReflectPromptResponse
} from './types';

const CHIP_CLASS = 'flowquest-chip';
const PANEL_CLASS = 'flowquest-cellPanel';
const ROOT_CLASS = 'flowquest-cellRoot';

export interface CellDecoratorCallbacks {
  applyState: (state: QuestState) => void;
  getState: () => QuestState;
  onXpGained: (amount: number, category: string, source: string) => void;
  getNotebookPath: () => string;
  getAnalysis: () => AnalysisResponse | null;
  openSidebar: () => void;
}

interface CellEntry {
  cell: Cell;
  chip: HTMLElement;
  panel: HTMLElement;
  panelOpen: boolean;
  cellIndex: number;
  analysis: CellAnalysis | null;
  missions: Mission[];
  explanation: string;
  reflectQuestion: string;
  reflectText: string;
  loading: Set<string>;
  /** When the explain action errors out we keep the message so we can show
   * a friendly inline error with a retry button. Cleared on the next attempt. */
  explainError: { kind: string; message: string } | null;
  /** Same idea for the reflect prompt fetch. */
  reflectError: { kind: string; message: string } | null;
  /** Per-mission claim error so we don't overwrite the explanation block. */
  claimErrors: Map<string, string>;
}

export class CellDecorator {
  constructor(private panel: NotebookPanel, private callbacks: CellDecoratorCallbacks) {
    this.attachAll();
    this.panel.content.model?.cells.changed.connect(() => this.attachAll());
    this.panel.disposed.connect(() => this.dispose());
  }

  dispose(): void {
    this.entries.forEach(entry => {
      entry.chip.remove();
      entry.panel.remove();
      entry.cell.node.classList.remove(ROOT_CLASS);
    });
    this.entries.clear();
  }

  refresh(analysis: AnalysisResponse | null, _state?: QuestState): void {
    this.attachAll();
    const widgets = this.panel.content.widgets;
    widgets.forEach((cell, index) => {
      const entry = this.entries.get(cell);
      if (!entry) {
        return;
      }
      entry.cellIndex = index;
      entry.analysis = analysis?.cells.find(c => c.index === index) ?? null;
      entry.missions = (analysis?.missions ?? []).filter(m => m.cell_indices.includes(index));
      this.renderChip(entry);
      if (entry.panelOpen) {
        this.renderPanel(entry);
      }
    });
  }

  private attachAll(): void {
    const widgets = this.panel.content.widgets;
    widgets.forEach((cell, index) => {
      if (this.entries.has(cell)) {
        const entry = this.entries.get(cell)!;
        entry.cellIndex = index;
        return;
      }
      this.attachCell(cell, index);
    });
    // Clean up entries for removed cells.
    Array.from(this.entries.keys()).forEach(cell => {
      if (cell.isDisposed || !widgets.includes(cell)) {
        const entry = this.entries.get(cell)!;
        entry.chip.remove();
        entry.panel.remove();
        this.entries.delete(cell);
      }
    });
  }

  private attachCell(cell: Cell, index: number): void {
    cell.node.classList.add(ROOT_CLASS);

    const chip = document.createElement('div');
    chip.className = CHIP_CLASS;
    chip.setAttribute('role', 'button');
    chip.setAttribute('tabindex', '0');

    const panel = document.createElement('div');
    panel.className = PANEL_CLASS;
    panel.style.display = 'none';
    // The panel lives inside the notebook DOM, where JupyterLab intercepts
    // mouse/keyboard events to drive cell focus + command-mode shortcuts. That
    // stops our inputs (the reflect textarea) from gaining focus / receiving
    // keystrokes. Contain those events within the panel so its form controls
    // behave like normal HTML.
    const contain = (event: Event) => event.stopPropagation();
    [
      'mousedown',
      'mouseup',
      'click',
      'dblclick',
      'keydown',
      'keyup',
      'keypress',
      'contextmenu',
      'focusin',
      'focusout'
    ].forEach(type => panel.addEventListener(type, contain));

    // Mount chip at top of cell.node and panel after the input container.
    const inputWrapper = cell.node.querySelector('.jp-Cell-inputWrapper') ?? cell.node;
    inputWrapper.parentElement?.insertBefore(chip, inputWrapper);
    inputWrapper.parentElement?.insertBefore(panel, inputWrapper.nextSibling);

    const entry: CellEntry = {
      cell,
      chip,
      panel,
      panelOpen: false,
      cellIndex: index,
      analysis: null,
      missions: [],
      explanation: '',
      reflectQuestion: '',
      reflectText: '',
      loading: new Set(),
      explainError: null,
      reflectError: null,
      claimErrors: new Map()
    };
    this.entries.set(cell, entry);

    chip.addEventListener('click', () => this.togglePanel(entry));
    chip.addEventListener('keydown', event => {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        this.togglePanel(entry);
      }
    });

    this.renderChip(entry);
  }

  private togglePanel(entry: CellEntry): void {
    entry.panelOpen = !entry.panelOpen;
    entry.panel.style.display = entry.panelOpen ? 'block' : 'none';
    if (entry.panelOpen) {
      this.renderPanel(entry);
    }
    this.renderChip(entry);
  }

  private renderChip(entry: CellEntry): void {
    const analysis = entry.analysis;
    const region = analysis?.region ?? 'other';
    const regionGlyph = renderRegionIcon(region);
    const issues = analysis?.issues ?? [];
    const worstSeverity = issues.reduce<string>((acc, issue) => {
      if (issue.severity === 'error') {
        return 'error';
      }
      if (issue.severity === 'warn' && acc !== 'error') {
        return 'warn';
      }
      if (issue.severity === 'info' && acc === '') {
        return 'info';
      }
      return acc;
    }, '');
    const missionCount = entry.missions.length;
    const healthClass = worstSeverity ? `is-${worstSeverity}` : 'is-ok';

    entry.chip.innerHTML = `
      <span class="flowquest-chipIcon">${regionGlyph}</span>
      <span class="flowquest-chipLabel">${escapeHtml(region)}</span>
      <span class="flowquest-chipDot ${healthClass}" title="${escapeHtml(
        worstSeverity ? `Has ${worstSeverity} issue(s)` : 'No issues detected'
      )}"></span>
      ${
        missionCount
          ? `<span class="flowquest-chipStar" title="${missionCount} mission${
              missionCount === 1 ? '' : 's'
            } for this cell">${renderUiIcon('star')} ${missionCount}</span>`
          : ''
      }
      <span class="flowquest-chipToggle">${
        entry.panelOpen ? renderUiIcon('chevronDown') : renderUiIcon('chevronRight')
      }</span>
    `;
    entry.chip.classList.toggle('is-open', entry.panelOpen);
    entry.chip.classList.toggle('has-issues', Boolean(worstSeverity));
    entry.chip.classList.toggle('has-mission', missionCount > 0);
  }

  private renderPanel(entry: CellEntry): void {
    const analysis = entry.analysis;
    const issues = analysis?.issues ?? [];
    const missions = entry.missions;
    const loadingExplain = entry.loading.has('explain');
    const loadingReflect = entry.loading.has('reflect');
    const loadingSubmit = entry.loading.has('submitReflect');
    const loadingMission = (id: string) => entry.loading.has(`claim-${id}`);

    const region = analysis?.region ?? 'other';
    const regionGlyph = renderRegionIcon(region);

    // ---- Facts pills -----------------------------------------------------
    const facts: string[] = [];
    if (analysis) {
      if (analysis.execCount !== null) {
        facts.push(`<span class="flowquest-fact">exec #${analysis.execCount}</span>`);
      } else {
        facts.push('<span class="flowquest-fact is-warn">not executed</span>');
      }
      if (analysis.defines.length) {
        facts.push(
          `<span class="flowquest-fact">defines ${escapeHtml(
            analysis.defines.slice(0, 6).join(', ')
          )}</span>`
        );
      }
      if (analysis.uses.length) {
        facts.push(
          `<span class="flowquest-fact">uses ${escapeHtml(
            analysis.uses.slice(0, 6).join(', ')
          )}</span>`
        );
      }
      if (analysis.dependsOn.length) {
        facts.push(
          `<span class="flowquest-fact">← cell${
            analysis.dependsOn.length > 1 ? 's' : ''
          } ${analysis.dependsOn.map(i => i + 1).join(', ')}</span>`
        );
      }
      if (analysis.dependents.length) {
        facts.push(
          `<span class="flowquest-fact">→ cell${
            analysis.dependents.length > 1 ? 's' : ''
          } ${analysis.dependents.map(i => i + 1).join(', ')}</span>`
        );
      }
    }

    // ---- Issues ---------------------------------------------------------
    const issueHtml = issues
      .map(
        issue => `
          <li class="flowquest-issue flowquest-issue-${escapeHtml(issue.severity)}">
            <span class="flowquest-issueIcon">${renderUiIcon(
              issue.severity === 'error'
                ? 'error'
                : issue.severity === 'warn'
                  ? 'warn'
                  : 'info'
            )}</span>
            <span class="flowquest-issueBody">
              <strong>${escapeHtml(issue.kind.replace(/_/g, ' '))}</strong>
              <span>${escapeHtml(issue.message)}</span>
            </span>
          </li>
        `
      )
      .join('');

    // ---- Explain card ---------------------------------------------------
    const explainCard = (() => {
      let body: string;
      if (loadingExplain) {
        body = renderThinking('Thinking about this cell…');
      } else if (entry.explainError) {
        body = renderInlineError(entry.explainError, 'retry-explain');
      } else if (entry.explanation) {
        body = `<div class="flowquest-block flowquest-md">${renderMarkdown(entry.explanation)}</div>`;
      } else {
        body = `<div class="flowquest-cardHint">Get a short, contextual explanation grounded in the surrounding cells.</div>`;
      }
      return `
        <section class="flowquest-cellSection">
          <header class="flowquest-cellSectionHead">
            <span class="flowquest-cellSectionIcon">${renderUiIcon('explain')}</span>
            <span class="flowquest-cellSectionTitle">Explain this cell</span>
            <span class="flowquest-cellSectionMeta">+3 XP (first time per cell)</span>
          </header>
          ${body}
          <div class="flowquest-actionsRow">
            <button
              type="button"
              class="flowquest-btn flowquest-btn-primary"
              data-action="explain"
              ${loadingExplain ? 'disabled' : ''}
            >${
              loadingExplain
                ? renderInlineSpinner('Thinking…')
                : entry.explanation
                  ? `${renderUiIcon('refresh')} Re-explain`
                  : `${renderUiIcon('explain')} Explain`
            }</button>
          </div>
        </section>
      `;
    })();

    // ---- Reflect card ---------------------------------------------------
    const reflectCard = (() => {
      let body: string;
      if (loadingReflect) {
        body = renderThinking('Composing a reflective question…');
      } else if (entry.reflectError) {
        body = renderInlineError(entry.reflectError, 'retry-reflect');
      } else if (entry.reflectQuestion) {
        body = `
          <div class="flowquest-block">${escapeHtml(entry.reflectQuestion)}</div>
          <textarea
            class="flowquest-textarea"
            data-field="reflect"
            placeholder="Write a sentence or two. +6 XP on submit."
          >${escapeHtml(entry.reflectText)}</textarea>
          <div class="flowquest-actionsRow">
            <button
              type="button"
              class="flowquest-btn flowquest-btn-primary"
              data-action="submitReflect"
              ${loadingSubmit || !entry.reflectText.trim() ? 'disabled' : ''}
            >${
              loadingSubmit ? renderInlineSpinner('Saving…') : 'Submit reflection'
            }</button>
          </div>
        `;
      } else {
        body = `<div class="flowquest-cardHint">Get one short, pointed question about a design choice in this cell.</div>`;
      }
      return `
        <section class="flowquest-cellSection">
          <header class="flowquest-cellSectionHead">
            <span class="flowquest-cellSectionIcon">${renderUiIcon('reflect')}</span>
            <span class="flowquest-cellSectionTitle">Reflect</span>
            <span class="flowquest-cellSectionMeta">+6 XP on first reflection</span>
          </header>
          ${body}
          ${
            !loadingReflect && !entry.reflectQuestion && !entry.reflectError
              ? `
                <div class="flowquest-actionsRow">
                  <button type="button" class="flowquest-btn" data-action="reflect">${renderUiIcon('reflect')} Get a question</button>
                </div>
              `
              : ''
          }
        </section>
      `;
    })();

    // ---- Missions -------------------------------------------------------
    const missionHtml = missions
      .map(mission => {
        const state = this.callbacks.getState();
        const awardPrefix = notebookAwardPrefix(state.notebookPath);
        const completed = (state.completedAwardKeys ?? []).includes(
          `${awardPrefix}mission:${mission.id}`
        );
        const loadingThis = loadingMission(mission.id);
        const points = mission.xp;
        const claimError = entry.claimErrors.get(mission.id);
        return `
          <li class="flowquest-missionCard flowquest-mission-${escapeHtml(mission.kind)} ${
            completed ? 'is-complete' : ''
          }">
            <div class="flowquest-missionHead">
              <span class="flowquest-missionKind">${categoryIcon(
                mission.kind
              )} ${escapeHtml(mission.kind)}</span>
              <span class="flowquest-missionXp">+${points} XP</span>
            </div>
            <div class="flowquest-missionTitle">${escapeHtml(mission.title)}</div>
            <div class="flowquest-missionDesc">${escapeHtml(mission.description)}</div>
            ${
              claimError
                ? `<div class="flowquest-inlineError flowquest-inlineError-compact">${escapeHtml(claimError)}</div>`
                : ''
            }
            <div class="flowquest-missionActions">
              <button
                type="button"
                class="flowquest-btn flowquest-btn-primary"
                data-action="claim"
                data-mission="${escapeHtml(mission.id)}"
                data-category="${escapeHtml(mission.kind)}"
                data-points="${points}"
                data-label="${escapeHtml(mission.title)}"
                ${completed || loadingThis ? 'disabled' : ''}
              >${
                completed
                  ? `${renderUiIcon('check')} Claimed`
                  : loadingThis
                    ? renderInlineSpinner('Claiming…')
                    : `Claim +${points}`
              }</button>
            </div>
          </li>
        `;
      })
      .join('');

    entry.panel.innerHTML = `
      <div class="flowquest-cellPanelInner flowquest-cellPanel-region-${escapeHtml(region)}">
        <header class="flowquest-cellPanelHead">
          <div class="flowquest-cellPanelHeadLeft">
            <span class="flowquest-cellPanelBadge">Cell ${entry.cellIndex + 1}</span>
            <span class="flowquest-cellPanelRegion">
              <span class="flowquest-cellPanelRegionIcon">${regionGlyph}</span>
              <span class="flowquest-cellPanelRegionLabel">${escapeHtml(region)}</span>
            </span>
          </div>
          <div class="flowquest-cellPanelHeadRight">
            <button type="button" class="flowquest-btn flowquest-btn-ghost" data-action="openSidebar">
              Open FlowQuest ${renderUiIcon('open')}
            </button>
            <button type="button" class="flowquest-btn flowquest-btn-ghost" data-action="close" title="Close">${renderUiIcon('close')}</button>
          </div>
        </header>

        ${
          analysis
            ? `<div class="flowquest-factRow">${facts.join('')}</div>`
            : '<div class="flowquest-dim">FlowQuest analysis is still loading for this cell.</div>'
        }

        ${
          issues.length
            ? `
              <section class="flowquest-cellSection">
                <header class="flowquest-cellSectionHead">
                  <span class="flowquest-cellSectionIcon">${renderUiIcon('diagnostics')}</span>
                  <span class="flowquest-cellSectionTitle">Issues</span>
                  <span class="flowquest-cellSectionMeta">${issues.length}</span>
                </header>
                <ul class="flowquest-issueList">${issueHtml}</ul>
              </section>
            `
            : ''
        }

        ${explainCard}
        ${reflectCard}

        ${
          missions.length
            ? `
              <section class="flowquest-cellSection">
                <header class="flowquest-cellSectionHead">
                  <span class="flowquest-cellSectionIcon">${renderUiIcon('missions')}</span>
                  <span class="flowquest-cellSectionTitle">Missions</span>
                  <span class="flowquest-cellSectionMeta">${missions.length}</span>
                </header>
                <ul class="flowquest-missionList">${missionHtml}</ul>
              </section>
            `
            : ''
        }
      </div>
    `;

    const textarea = entry.panel.querySelector<HTMLTextAreaElement>('textarea[data-field="reflect"]');
    if (textarea) {
      textarea.addEventListener('input', event => {
        entry.reflectText = (event.currentTarget as HTMLTextAreaElement).value;
        // Re-render to enable/disable the submit button based on text.
        // We avoid a full panel rerender (which would steal focus); just toggle.
        const submitBtn = entry.panel.querySelector<HTMLButtonElement>(
          'button[data-action="submitReflect"]'
        );
        if (submitBtn) {
          submitBtn.disabled = entry.reflectText.trim().length === 0;
        }
      });
      // Keep JupyterLab's command-mode keyboard shortcuts from swallowing
      // keystrokes meant for this injected textarea.
      const stop = (event: Event) => event.stopPropagation();
      textarea.addEventListener('keydown', stop);
      textarea.addEventListener('keypress', stop);
      textarea.addEventListener('keyup', stop);
    }

    entry.panel.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(button => {
      button.onclick = () => this.handleAction(entry, button);
    });
  }

  private async handleAction(entry: CellEntry, button: HTMLButtonElement): Promise<void> {
    const action = button.dataset.action;
    if (action === 'close') {
      entry.panelOpen = false;
      entry.panel.style.display = 'none';
      this.renderChip(entry);
      return;
    }
    if (action === 'openSidebar') {
      this.callbacks.openSidebar();
      return;
    }
    if (action === 'explain') {
      await this.runExplain(entry);
      return;
    }
    if (action === 'reflect') {
      await this.runReflect(entry);
      return;
    }
    if (action === 'submitReflect') {
      await this.submitReflect(entry);
      return;
    }
    if (action === 'claim') {
      const missionId = button.dataset.mission ?? '';
      const category = button.dataset.category ?? 'exploration';
      const points = Number(button.dataset.points ?? '0');
      const label = button.dataset.label ?? missionId;
      await this.claim(entry, missionId, category, points, label);
      return;
    }
    if (action === 'retry-explain') {
      entry.explainError = null;
      await this.runExplain(entry);
      return;
    }
    if (action === 'retry-reflect') {
      entry.reflectError = null;
      await this.runReflect(entry);
      return;
    }
  }

  private async runExplain(entry: CellEntry): Promise<void> {
    const source = entry.cell.model.sharedModel.getSource();
    if (!source.trim()) {
      entry.explanation = 'This cell is empty. Add code or text first.';
      entry.explainError = null;
      this.renderPanel(entry);
      return;
    }
    entry.loading.add('explain');
    entry.explainError = null;
    this.renderPanel(entry);
    try {
      const response = await apiRequest<ExplainResponse>('piis-assistant/explain-cell', {
        method: 'POST',
        body: JSON.stringify({
          state: this.callbacks.getState(),
          notebookPath: this.callbacks.getNotebookPath(),
          cell: {
            index: entry.cellIndex,
            region: entry.analysis?.region ?? 'other',
            source: clipText(source, 3000)
          },
          analysis: this.callbacks.getAnalysis()
        })
      });
      entry.explanation = response.explanation || 'No explanation returned.';
      if (response.outcome?.granted && response.outcome.xpAwarded) {
        this.callbacks.onXpGained(response.outcome.xpAwarded, 'exploration', 'Explain cell');
      }
      if (response.state) {
        this.callbacks.applyState(response.state);
      }
    } catch (error) {
      entry.explainError = toFriendlyError(error);
    } finally {
      entry.loading.delete('explain');
      this.renderPanel(entry);
    }
  }

  private async runReflect(entry: CellEntry): Promise<void> {
    const source = entry.cell.model.sharedModel.getSource();
    entry.loading.add('reflect');
    entry.reflectError = null;
    this.renderPanel(entry);
    try {
      const response = await apiRequest<ReflectPromptResponse>('piis-assistant/reflect/prompt', {
        method: 'POST',
        body: JSON.stringify({
          cell: {
            index: entry.cellIndex,
            region: entry.analysis?.region ?? 'other',
            source: clipText(source, 2500)
          },
          difficulty: this.callbacks.getState().difficulty
        })
      });
      entry.reflectQuestion = response.question || 'What could go wrong with this cell?';
    } catch (error) {
      entry.reflectError = toFriendlyError(error);
    } finally {
      entry.loading.delete('reflect');
      this.renderPanel(entry);
    }
  }

  private async submitReflect(entry: CellEntry): Promise<void> {
    const text = entry.reflectText.trim();
    if (!text) {
      return;
    }
    entry.loading.add('submitReflect');
    this.renderPanel(entry);
    try {
      const response = await apiRequest<ClaimResponse>('piis-assistant/reflect/answer', {
        method: 'POST',
        body: JSON.stringify({
          state: this.callbacks.getState(),
          notebookPath: this.callbacks.getNotebookPath(),
          cellIndex: entry.cellIndex,
          text
        })
      });
      if (response.outcome?.granted) {
        this.callbacks.onXpGained(
          response.outcome.xpAwarded ?? 0,
          'reflection',
          'Reflection'
        );
      }
      this.callbacks.applyState(response.state);
      entry.reflectText = '';
      entry.reflectQuestion = `Reflection saved · ${entry.reflectQuestion}`;
    } catch (error) {
      entry.reflectError = toFriendlyError(error);
    } finally {
      entry.loading.delete('submitReflect');
      this.renderPanel(entry);
    }
  }

  private async claim(
    entry: CellEntry,
    missionId: string,
    category: string,
    points: number,
    label: string
  ): Promise<void> {
    entry.loading.add(`claim-${missionId}`);
    entry.claimErrors.delete(missionId);
    this.renderPanel(entry);
    try {
      const response = await apiRequest<ClaimResponse>('piis-assistant/mission/claim', {
        method: 'POST',
        body: JSON.stringify({
          state: this.callbacks.getState(),
          notebookPath: this.callbacks.getNotebookPath(),
          missionId,
          category,
          xp: points,
          label
        })
      });
      if (response.outcome?.granted) {
        this.callbacks.onXpGained(
          response.outcome.xpAwarded ?? 0,
          response.outcome.category ?? category,
          missionId
        );
      }
      this.callbacks.applyState(response.state);
    } catch (error) {
      const friendly = toFriendlyError(error);
      entry.claimErrors.set(missionId, friendly.message);
    } finally {
      entry.loading.delete(`claim-${missionId}`);
      this.renderPanel(entry);
    }
  }

  private entries = new Map<Cell, CellEntry>();
}

// ---------------------------------------------------------------------------
// Render helpers (HTML strings)
// ---------------------------------------------------------------------------

const renderInlineSpinner = inlineSpinnerHtml;
const renderThinking = thinkingHtml;

function renderInlineError(
  err: { kind: string; message: string },
  retryAction: string
): string {
  return errorBlockHtml(err, { retryAction, retryLabel: 'Retry' });
}
